### ISSUE TITLE
UI Designing

### ISSUE THREAD

**Issue by DeveloperSpoot** [codyseibert/online-classroom#10]
**UI PAGES**

- [ ] Login Screen
- [x] Role Selection Screen
- [x] Teacher Wizard
- [x] Student Wizard
- [ ] Dashboard Teacher
- [ ] Dashboard Student
- [ ] Assignments Teacher
- [ ] Assignments Student
- [ ] Students Management
- [ ] Course Management

**UI Components**

- [ ] Navbar
- [ ] Splash Screen
- [ ] Logo
- [ ] Buttons
- [ ] Dropdown
- [ ] Text areas
- [ ] File input

**Other**
- [x] Color Palette
- [x] Font

**UI Link (Requires free download)**
https://lun-us.icons8.com/d/QS8VsoQN3UCJ7BY7iDmEKQ?page=tMHnVAOTykizxsXWzjEwVA&vp=486,751,1690,1368

**Comment by DeveloperSpoot** [comment]
**Color Palette**
_Advice would be to set up global color variables._

![Image](https://user-images.githubusercontent.com/52226518/180593246-72dbe5a1-d28c-49be-9814-0289cc2a4dc7.png)

**Comment by DeveloperSpoot** [comment]
I added color variables to the tailWind config file.

![Image](https://user-images.githubusercontent.com/52226518/180624858-b38e9bff-af29-4c00-a61a-9a74a8c247be.png)

**Comment by DeveloperSpoot** [comment]
For the font, going to use Poppins.

**Comment by DeveloperSpoot** [comment]
Role selection screen: 
![Role Selection](https://user-images.githubusercontent.com/52226518/180629776-16adeacf-55da-4d11-b5a0-98c6ea37ac56.png)

**Comment by DeveloperSpoot** [comment]
**Primary Button Component.**

- Normal
- Hover
- Disabled

![Image](https://i.imgur.com/OItcfZe.png)

**Comment by DeveloperSpoot** [comment]
**Teacher Wizard**
Darft.js is what will be replacing the description. Not sure if that can be styled to look like the concept.
![Teacher Wizard](https://user-images.githubusercontent.com/52226518/180629796-99a2d7eb-06b6-4f4d-bf08-05a1847169e5.png)

**Comment by Jaival** [comment]
I have designed NavBar component and login page as per my understanding. Let me know if I need to make any changes.

### Login Screen
![Login Screen](https://user-images.githubusercontent.com/34303559/185785106-87778175-3827-455d-a704-a345579b3044.png)

### Navbar Component
![Navbar-Component](https://user-images.githubusercontent.com/34303559/185785230-4cdfc197-237f-440b-b2b0-227884bd8d26.png)

**Comment by Jaival** [comment]
Next, I will go with student and teacher dashboards. From what I understand:

For student,
1. It will show the all classroom they have currently enrolled in. [List of cards I am thinking]
2. they will also have completed classrooms for the previous year or semester.[List of grayed cards I am thinking]
3. Join classroom button.

For Teachers (similar to students),
1. It will show the all classroom they have currently created and the number of students enrolled.
2. they will also have completed classrooms for the previous year or semester.
4. Create classroom button.

Let me know if I am missing something.

**Comment by homiecoder** [comment]
Are you looking for any help with these issues?
